version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - pwd && cd aws-embedded-metrics
      - npm install
  build:
    commands:
      - pwd
      - npm run lint
      - npm run build
